name: 'Status checker'

on: 
  pull_request_target:
    types: apiversion

jobs:
  status_checker_job:
    name: Look for build warnings
    runs-on: ubuntu-latest
    permissions:
        statuses: write
        issues: write
        pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - uses: dotnet/docs-tools/actions/status-checker@main
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        docs_path: "Contribute"
        url_base_path: "contribute"
